--require('plugins.packer')
require('plugins.lazynvim')
require('plugins.ui')
require('plugins.telescope')
require('plugins.treesitter')
require('plugins.neotree')
-- require('plugins.nvimtree')
require('plugins.edit')
require('plugins.terminal')
